### ISSUE TITLE
Create endpoint to evaluate performance of the catalyst

### ISSUE THREAD

**Issue by menduz** [decentraland/explorer-bff#43]
The endpoint will serve two purposes:
1. Get the status of the network behind this BFF
2. Get the configurations for this instance of Decentraland like
   - Content server to be used
   - Is it a DCL space? should it load the genesis city? something else?
   - Feature flags
   - Sky, physics, limitations configuration
   - etc

This endpoint should work to configure the explorer for the current lighthouse-based comms and for the new bff based comms. The way it will work is by specifying the `commsProtocol` in the `.configurations` property.

```HTTP
GET /explorer-configuration

{
  "healthy": true,
  "featureFlags": { ... },
  "configurations": {
    "commsProtocol": "v2",
    "stun": ["stun:..."]
  },
  "system": {
    "content": {
      "baseUrl": "https://peer.decentraland.org/content",
      "health": "HEALTHY"
    },
    "comms": {
      "baseUrl": "https://peer.decentraland.org/comms",
      "health": "HEALTHY"
    },
    "turn": {
      "baseUrl": "tcp://123.123.123.123",
      "health": "HEALTHY"
    },
    ...
  }
}
```

**Comment by juanscolari** [comment]
Implemented `explorer-configuration` endpoint with `configurations.commsProtocol` here: https://github.com/decentraland/explorer-bff/pull/87

**Comment by hugoArregui** [comment]
although we may need to iterate on the content, we now have the /about endpoint
